[build]
rustflags = ["-Z", "threads=8"]

[target.'cfg(target_arch = "wasm32")']
rustflags = [
  "-Zthreads=8",
  "-Zwasm-c-abi=spec",
  "--cfg=web_sys_unstable_apis",
  "--cfg=getrandom_backend=\"wasm_js\"",
]
